version: '3.9'

services:

  mysql:
    build: ./database
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./Backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  frontend:
    build: ./Frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql-data: