FROM mysql:8.0

ENV MYSQL_ROOT_PASSWORD=rootroot
ENV MYSQL_DATABASE=ClickNcart


# MySQL's official image auto-runs any .sql file placed here on first boot
COPY init.sql /docker-entrypoint-initdb.d/init.sql

EXPOSE 3306
