spring.application.name=ClickNcart

# database
spring.datasource.url=jdbc:mysql://mysql:3306/ClickNcart
spring.datasource.username=root
spring.datasource.password=rootroot

# JPA 
spring.jpa.hibernate.ddl-auto=update
#optional
spring.jpa.show-sql=true
spring.jpa.properties.format_sql=true

# Error
#spring.web.error.include-message=always
server.error.include-message=always

# API
spring.data.rest.base-path=/api

# RazorPay
razorpay.key_id=rzp_test_SXLPyp2eitE0Px
razorpay.key_secret=6w8f0gbfMZyNat6YH7FDFtUM


# Frontend 
origin=http://localhost

