spring.application.name=ClickNcart
spring.datasource.url=jdbc:mysql://database-1.csd8s4wqyqd0.us-east-1.rds.amazonaws.com:3306/ClickNcart
spring.datasource.username=root
spring.datasource.password=rootroot
spring.jpa.hibernate.ddl-auto=update
#optional
spring.jpa.show-sql=true
spring.jpa.properties.format_sql=true
#spring.web.error.include-message=always
server.error.include-message=always

spring.data.rest.base-path=/api
razorpay.key_id=rzp_test_SXLPyp2eitE0Px
razorpay.key_secret=6w8f0gbfMZyNat6YH7FDFtUM

origin=http:54.90.153.251:3000
